/**
 * Metro / display city names for IATA codes — pairing detail layover hero (schedule import only
 * guarantees airport codes; hotel rows refine neighborhood).
 */

const IATA_TO_METRO: Record<string, string> = {
  JFK: 'New York',
  LGA: 'New York',
  EWR: 'Newark',
  BOS: 'Boston',
  BWI: 'Baltimore',
  IAD: 'Washington DC',
  DCA: 'Washington DC',
  FLL: 'Fort Lauderdale',
  MCO: 'Orlando',
  MIA: 'Miami',
  TPA: 'Tampa',
  RSW: 'Fort Myers',
  JAX: 'Jacksonville',
  PBI: 'West Palm Beach',
  LAX: 'Los Angeles',
  SFO: 'San Francisco',
  SAN: 'San Diego',
  OAK: 'Oakland',
  SJC: 'San Jose',
  SNA: 'Orange County',
  BUR: 'Burbank',
  SEA: 'Seattle',
  PDX: 'Portland',
  DEN: 'Denver',
  ORD: 'Chicago',
  MDW: 'Chicago',
  IAH: 'Houston',
  HOU: 'Houston',
  ATL: 'Atlanta',
  DTW: 'Detroit',
  MSP: 'Minneapolis',
  SLC: 'Salt Lake City',
  PHX: 'Phoenix',
  LAS: 'Las Vegas',
  CLT: 'Charlotte',
  DFW: 'Dallas',
  DAL: 'Dallas',
  STL: 'St. Louis',
  MCI: 'Kansas City',
  MSY: 'New Orleans',
  ANC: 'Anchorage',
  HNL: 'Honolulu',
  OGG: 'Maui',
  LIH: 'Kauai',
  KOA: 'Kailua-Kona',
  BUF: 'Buffalo',
  ROC: 'Rochester',
  SYR: 'Syracuse',
  ALB: 'Albany',
  CLE: 'Cleveland',
  CMH: 'Columbus',
  CVG: 'Cincinnati',
  IND: 'Indianapolis',
  MKE: 'Milwaukee',
  RDU: 'Raleigh',
  BNA: 'Nashville',
  AUS: 'Austin',
  SAT: 'San Antonio',
  MEX: 'Mexico City',
  CUN: 'Cancún',
  SJD: 'Los Cabos',
  PVR: 'Puerto Vallarta',
  GDL: 'Guadalajara',
  TUN: 'Providenciales',
  SXM: 'St. Martin',
  AUA: 'Aruba',
  SJU: 'San Juan',
  STT: 'St. Thomas',
  STX: 'St. Croix',
  NAS: 'Nassau',
  DUB: 'Dublin',
  LHR: 'London',
  LGW: 'London',
  STN: 'London',
  MAN: 'Manchester',
  EDI: 'Edinburgh',
  CDG: 'Paris',
  ORY: 'Paris',
  AMS: 'Amsterdam',
  BRU: 'Brussels',
  MAD: 'Madrid',
  BCN: 'Barcelona',
  LIS: 'Lisbon',
  OPO: 'Porto',
  FCO: 'Rome',
  MXP: 'Milan',
  ZRH: 'Zurich',
  GVA: 'Geneva',
  FRA: 'Frankfurt',
  MUC: 'Munich',
  DUS: 'Düsseldorf',
  TXL: 'Berlin',
  BER: 'Berlin',
  ARN: 'Stockholm',
  CPH: 'Copenhagen',
  OSL: 'Oslo',
  HEL: 'Helsinki',
  KEF: 'Reykjavík',
  NCE: 'Nice',
  VCE: 'Venice',
  ATH: 'Athens',
  IST: 'Istanbul',
  TLV: 'Tel Aviv',
  DXB: 'Dubai',
  AUH: 'Abu Dhabi',
  DOH: 'Doha',
  CAI: 'Cairo',
  CMN: 'Casablanca',
  JNB: 'Johannesburg',
  CPT: 'Cape Town',
  NRT: 'Tokyo',
  HND: 'Tokyo',
  ICN: 'Seoul',
  PEK: 'Beijing',
  PVG: 'Shanghai',
  HKG: 'Hong Kong',
  SIN: 'Singapore',
  BKK: 'Bangkok',
  SYD: 'Sydney',
  MEL: 'Melbourne',
  AKL: 'Auckland',
  BOG: 'Bogotá',
  LIM: 'Lima',
  SCL: 'Santiago',
  EZE: 'Buenos Aires',
  GRU: 'São Paulo',
  GIG: 'Rio de Janeiro',
  YYZ: 'Toronto',
  YVR: 'Vancouver',
  YUL: 'Montreal',
  SAL: 'San Salvador',
};

export function metroCityForIata(raw: string | null | undefined): string | null {
  const c = String(raw ?? '')
    .trim()
    .toUpperCase();
  if (!/^[A-Z]{3}$/.test(c)) return null;
  return IATA_TO_METRO[c] ?? null;
}
